class BirthCertificateRunner{
	public static void main(String[] birthCertificate){
		BirthCertificate baby1 = new BirthCertificate();
		baby1.name = "ABC";
		baby1.gender = 'M';
		baby1.dob = "01-01-2000";
		baby1.fatherName = "qwerty";
		baby1.motherName = "qwerty";
		baby1.address = "zzzzzzzzzzzzz";
		System.out.println("Baby1 Name: "+baby1.name);
		System.out.println("Baby1 Gender: "+baby1.gender);
		System.out.println("Baby1 DOB: "+baby1.dob);
		System.out.println("Baby1 Father Name: "+baby1.fatherName);
		System.out.println("Baby1 Mother Name: "+baby1.motherName);
		System.out.println("Baby1 Address: "+baby1.address);
		BirthCertificate baby2 = new BirthCertificate();
		baby2.name = "ABC";
		baby2.gender = 'M';
		baby2.dob = "01-01-2000";
		baby2.fatherName = "qwerty";
		baby2.motherName = "qwerty";
		baby2.address = "zzzzzzzzzzzzz";
		System.out.println("Baby2 Name: "+baby2.name);
		System.out.println("Baby2 Gender: "+baby2.gender);
		System.out.println("Baby2 DOB: "+baby2.dob);
		System.out.println("Baby2 Father Name: "+baby2.fatherName);
		System.out.println("Baby2 Mother Name: "+baby2.motherName);
		System.out.println("Baby2 Address: "+baby2.address);
		BirthCertificate baby3 = new BirthCertificate();
		baby3.name = "ABC";
		baby3.gender = 'M';
		baby3.dob = "01-01-2000";
		baby3.fatherName = "qwerty";
		baby3.motherName = "qwerty";
		baby3.address = "zzzzzzzzzzzzz";
		System.out.println("Baby3 Name: "+baby3.name);
		System.out.println("Baby3 Gender: "+baby3.gender);
		System.out.println("Baby3 DOB: "+baby3.dob);
		System.out.println("Baby3 Father Name: "+baby3.fatherName);
		System.out.println("Baby3 Mother Name: "+baby3.motherName);
		System.out.println("Baby3 Address: "+baby3.address);
		BirthCertificate baby4 = new BirthCertificate();
		baby4.name = "ABC";
		baby4.gender = 'M';
		baby4.dob = "01-01-2000";
		baby4.fatherName = "qwerty";
		baby4.motherName = "qwerty";
		baby4.address = "zzzzzzzzzzzzz";
		System.out.println("Baby4 Name: "+baby4.name);
		System.out.println("Baby4 Gender: "+baby4.gender);
		System.out.println("Baby4 DOB: "+baby4.dob);
		System.out.println("Baby4 Father Name: "+baby4.fatherName);
		System.out.println("Baby4 Mother Name: "+baby4.motherName);
		System.out.println("Baby4 Address: "+baby4.address);
		BirthCertificate baby5 = new BirthCertificate();
		baby5.name = "ABC";
		baby5.gender = 'M';
		baby5.dob = "01-01-2000";
		baby5.fatherName = "qwerty";
		baby5.motherName = "qwerty";
		baby5.address = "zzzzzzzzzzzzz";
		System.out.println("Baby5 Name: "+baby5.name);
		System.out.println("Baby5 Gender: "+baby5.gender);
		System.out.println("Baby5 DOB: "+baby5.dob);
		System.out.println("Baby5 Father Name: "+baby5.fatherName);
		System.out.println("Baby5 Mother Name: "+baby5.motherName);
		System.out.println("Baby5 Address: "+baby5.address);
	}
}