class PassportRunner{
	public static void main(String[] passport){
		Passport person1 = new Passport();
		System.out.println("*************First Person Details*********************");
		person1.firstname = "Mohammed";
		person1.lastName = "Niyamath";
		person1.dob = "07-05-2005";
		person1.gender = 'M';
		person1.phNo = 7975106965l;
		person1.fatherName = "Mohammed Suban";
		person1.motherName = "Tasleem Banu";
		person1.address = "Mandya";
		person1.issueDate = "10-02-2026";
		person1.expireDate = "10-02-2036";
		System.out.println("PERSON1 First Name: "+person1.firstname);
		System.out.println("PERSON1 Last Name: "+person1.lastName);
		System.out.println("PERSON1 DOB: "+person1.dob);
		System.out.println("PERSON1 Gender: "+person1.gender);
		System.out.println("PERSON1 Phone Number: "+person1.phNo);
		System.out.println("PERSON1 Father Name: "+person1.fatherName);
		System.out.println("PERSON1 Mother Name: "+person1.motherName);
		System.out.println("PERSON1 Address: "+person1.address);
		System.out.println("PERSON1 Issued Date: "+person1.issueDate);
		System.out.println("PERSON1 Expire Date: "+person1.expireDate);
		Passport person2 = new Passport();
		System.out.println("*************Second Person Details*********************");
		person2.firstname = "Arziya";
		person2.lastName = "Banu";
		person2.dob = "31-10-2003";
		person2.gender = 'F';
		person2.phNo = 7676686629l;
		person2.fatherName = "Mohammed Suban";
		person2.motherName = "Tasleem Banu";
		person2.address = "Mandya";
		person2.issueDate = "10-02-2026";
		person2.expireDate = "10-02-2036";
		System.out.println("PERSON2 First Name: "+person2.firstname);
		System.out.println("PERSON2 Last Name: "+person2.lastName);
		System.out.println("PERSON2 DOB: "+person2.dob);
		System.out.println("PERSON2 Gender: "+person2.gender);
		System.out.println("PERSON2 Phone Number: "+person2.phNo);
		System.out.println("PERSON2 Father Name: "+person2.fatherName);
		System.out.println("PERSON2 Mother Name: "+person2.motherName);
		System.out.println("PERSON2 Address: "+person2.address);
		System.out.println("PERSON2 Issued Date: "+person2.issueDate);
		System.out.println("PERSON2 Expire Date: "+person2.expireDate);
        Passport person3 = new Passport();
		System.out.println("*************Third Person Details*********************");
		person3.firstname = "Shafiya";
		person3.lastName = "Banu";
		person3.dob = "17-07-2000";
		person3.gender = 'F';
		person3.phNo = 7259328786l;
		person3.fatherName = "Mohammed Suban";
		person3.motherName = "Tasleem Banu";
		person3.address = "Mandya";
		person3.issueDate = "10-02-2026";
		person3.expireDate = "10-02-2036";
		System.out.println("PERSON3 First Name: "+person3.firstname);
		System.out.println("PERSON3 Last Name: "+person3.lastName);
		System.out.println("PERSON3 DOB: "+person3.dob);
		System.out.println("PERSON3 Gender: "+person3.gender);
		System.out.println("PERSON3 Phone Number: "+person3.phNo);
		System.out.println("PERSON3 Father Name: "+person3.fatherName);
		System.out.println("PERSON3 Mother Name: "+person3.motherName);
		System.out.println("PERSON3 Address: "+person3.address);
		System.out.println("PERSON3 Issued Date: "+person3.issueDate);
		System.out.println("PERSON3 Expire Date: "+person3.expireDate);
		Passport person4 = new Passport();
		System.out.println("*************Fourth Person Details*********************");
		person4.firstname = "AAAA";
		person4.lastName = "BBBB";
		person4.dob = "01-01-2000";
		person4.gender = 'M';
		person4.phNo = 7975106965l;
		person4.fatherName = " QWERTY";
		person4.motherName = "QWERTYQWERTY";
		person4.address = "ZZZZZZZZZ";
		person4.issueDate = "01-02-2026";
		person4.expireDate = "01-02-2036";
		System.out.println("PERSON4 First Name: "+person4.firstname);
		System.out.println("PERSON4 Last Name: "+person4.lastName);
		System.out.println("PERSON4 DOB: "+person4.dob);
		System.out.println("PERSON4 Gender: "+person4.gender);
		System.out.println("PERSON4 Phone Number: "+person4.phNo);
		System.out.println("PERSON4 Father Name: "+person4.fatherName);
		System.out.println("PERSON4 Mother Name: "+person4.motherName);
		System.out.println("PERSON4 Address: "+person4.address);
		System.out.println("PERSON4 Issued Date: "+person4.issueDate);
		System.out.println("PERSON4 Expire Date: "+person4.expireDate);
		Passport person5 = new Passport();
		System.out.println("*************Fivth Person Details*********************");
		person5.firstname = "AAAA";
		person5.lastName = "BBBB";
		person5.dob = "01-01-2000";
		person5.gender = 'M';
		person5.phNo = 7975106965l;
		person5.fatherName = " QWERTY";
		person5.motherName = "QWERTYQWERTY";
		person5.address = "ZZZZZZZZZ";
		person5.issueDate = "01-02-2026";
		person5.expireDate = "01-02-2036";
		System.out.println("PERSON5 First Name: "+person5.firstname);
		System.out.println("PERSON5 Last Name: "+person5.lastName);
		System.out.println("PERSON5 DOB: "+person5.dob);
		System.out.println("PERSON5 Gender: "+person5.gender);
		System.out.println("PERSON5 Phone Number: "+person5.phNo);
		System.out.println("PERSON5 Father Name: "+person5.fatherName);
		System.out.println("PERSON5 Mother Name: "+person5.motherName);
		System.out.println("PERSON5 Address: "+person5.address);
		System.out.println("PERSON5 Issued Date: "+person5.issueDate);
		System.out.println("PERSON5 Expire Date: "+person5.expireDate);
		Passport person6 = new Passport();
		System.out.println("*************Sixth Person Details*********************");
		person6.firstname = "AAAA";
		person6.lastName = "BBBB";
		person6.dob = "01-01-2000";
		person6.gender = 'M';
		person6.phNo = 7975106965l;
		person6.fatherName = " QWERTY";
		person6.motherName = "QWERTYQWERTY";
		person6.address = "ZZZZZZZZZ";
		person6.issueDate = "01-02-2026";
		person6.expireDate = "01-02-2036";
		System.out.println("PERSON6 First Name: "+person6.firstname);
		System.out.println("PERSON6 Last Name: "+person6.lastName);
		System.out.println("PERSON6 DOB: "+person6.dob);
		System.out.println("PERSON6 Gender: "+person6.gender);
		System.out.println("PERSON6 Phone Number: "+person6.phNo);
		System.out.println("PERSON6 Father Name: "+person6.fatherName);
		System.out.println("PERSON6 Mother Name: "+person6.motherName);
		System.out.println("PERSON6 Address: "+person6.address);
		System.out.println("PERSON6 Issued Date: "+person6.issueDate);
		System.out.println("PERSON6 Expire Date: "+person6.expireDate);
	}
}